### PR TITLE
Initial port of library code to new library

### PR DESCRIPTION
**Pull request by madpah**

### CODE REVIEW

**Comment by madpah** [comment]
@DarthHater / @bhamail / @alindley 

Looking for any feedback at this point.

Library structure is in place with basic support across JSON and XML for schema versions 1.0 through 1.3. Would very much like to get this branch merged to master so we can consider:
1. Early release to PyPi - this allows `pip install ...` so we can start raising PR's for `jake` and the main cylconedx python application to use this library
2. Potential relocation of this library to CycloneDX GitHub org?
3. Getting into a release process for this library

Any and all comments welcome/apprectiated.

**Comment by DarthHater** [comment]
@coderpatros @stevespringett tagging you two for visibility on this! Pretty rad.

**Comment by DarthHater** [comment]
Big feedback:

- Let's use poetry if possible for packaging, managing deps. I think it's great in comparison to pip's warts
- Let's switch from CircleCI to GitHub Actions, that's how the rest of the CycloneDX stuff is setup, if we want to transfer it (we do!) it'll be good to be consistent
- LICENSE HEADERS :)
- License (Apache 2)

I'd say merge this to main when you feel like it, then @bhamail and I can likely start picking away at it too!

**Comment by madpah** [comment]
@DarthHater - added Poetry support and GitHub actions.

If acceptable, I'll cleanup CircleCI and PIP related stuff.

FYI: @bhamail

**Comment by DarthHater** [comment]
Rad!!!!

**Comment by madpah** [comment]
@DarthHater - ensured support now for Python 3.7+ (not checked 3.6 just yet as brew seems to have yanked support for it!).

**Comment by madpah** [comment]
Support for Python 3.6 confirmed now also @DarthHater

**Pull request merged**
